# -*- coding: utf-8 -*-
"""rps_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cXm33Wzcoi_IhmZeYaKkPs5LvMj9GA05
"""

import random
from enum import IntEnum

class Action(IntEnum) :
  Rock = 0
  Paper = 1
  Scissors = 2

def get_user_selection():
    choices = [f"{action.name}[{action.value}]" for action in Action]
    choices_str = ", ".join(choices)
    selection = int(input(f"Enter a choice ({choices_str}): "))
    action = Action(selection)
    return action

get_user_selection()

def get_computer_selection():
  selection = random.randint(0, len(Action)-1)
  action = Action(selection)
  return action

get_computer_selection()

def determine_winner(user_action, computer_action):
    if user_action == computer_action:
        print(f"Both players selected {user_action.name}. It's a tie!")
    elif user_action == Action.Rock:
        if computer_action == Action.Scissors:
            print("Rock smashes scissors! You win!")
        else:
            print("Paper covers rock! You lose.")
    elif user_action == Action.Paper:
        if computer_action == Action.Rock:
            print("Paper covers rock! You win!")
        else:
            print("Scissors cuts paper! You lose.")
    elif user_action == Action.Scissors:
        if computer_action == Action.Paper:
            print("Scissors cuts paper! You win!")
        else:
            print("Rock smashes scissors! You lose.")

while True :
  try :
    user_action = get_user_selection()
  except ValueError as e:
    range_str = f"[0,{len(Action)-1}]"
    print(f"Invalid selection. Enter a value in range {range_str}")
    continue

  computer_action = get_computer_selection()
  print(f"You : {user_action}, computer : {computer_action}")
  determine_winner(user_action, computer_action)

  play_again = input("Play again? (yes/no) : ")
  if play_again.lower() != "yes" :
    break